# .github/FUNDING.yml

github: # [username]
patreon: # 
open_collective: #
ko_fi: shaiiwaru
tidelift: # "npm/package-name"
community_bridge: # project-name
liberapay: # username
issuehunt: # username
polar: # username
thanks_dev: # username
custom: ["mailto:kaishua2@://gmail.com",  "https://paypal.me/KaielAmato"]
